-- Supabase Schema for MessMate

-- 1. Profiles Table (Extends Auth Users)
CREATE TABLE profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  role TEXT CHECK (role IN ('admin', 'manager', 'student')) DEFAULT 'student',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  status TEXT DEFAULT 'active'
);

-- 2. Messes Table
CREATE TABLE messes (
  id TEXT PRIMARY KEY, -- Mess code
  name TEXT,
  owner_id UUID REFERENCES auth.users NOT NULL,
  data JSONB DEFAULT '{}'::jsonb, -- Stores residents, meals, purchases, etc.
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  updated_by UUID REFERENCES auth.users
);

-- 3. Mess Members Table
CREATE TABLE mess_members (
  mess_id TEXT REFERENCES messes(id) ON DELETE CASCADE,
  user_id UUID REFERENCES auth.users ON DELETE CASCADE,
  PRIMARY KEY (mess_id, user_id)
);

-- 4. Manager Access Table (Month-wise)
CREATE TABLE manager_access (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  manager_id UUID REFERENCES auth.users ON DELETE CASCADE,
  mess_id TEXT REFERENCES messes(id) ON DELETE CASCADE,
  months TEXT[], -- Array of months like ['2024-01', '2024-02']
  granted_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  granted_by UUID REFERENCES auth.users
);

-- ENABLE ROW LEVEL SECURITY (RLS)
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE messes ENABLE ROW LEVEL SECURITY;
ALTER TABLE mess_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE manager_access ENABLE ROW LEVEL SECURITY;

-- RLS POLICIES

-- Profiles: Users can read their own profile
CREATE POLICY "Users can view own profile" ON profiles
  FOR SELECT USING (auth.uid() = id);

-- Profiles: Admins can view all profiles
CREATE POLICY "Admins can view all profiles" ON profiles
  FOR SELECT USING (
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
  );

-- Profiles: Admins can update profiles
CREATE POLICY "Admins can update profiles" ON profiles
  FOR UPDATE USING (
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
  );

-- Messes: Members can read mess data
CREATE POLICY "Members can view mess data" ON messes
  FOR SELECT USING (
    EXISTS (SELECT 1 FROM mess_members WHERE mess_id = messes.id AND user_id = auth.uid())
    OR EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
  );

-- Messes: Admins and Managers can update mess data
CREATE POLICY "Admins and Managers can update mess data" ON messes
  FOR UPDATE USING (
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
    OR (
      EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'manager')
      AND EXISTS (
        SELECT 1 FROM manager_access 
        WHERE manager_id = auth.uid() 
        AND mess_id = messes.id 
        AND (to_char(NOW(), 'YYYY-MM') = ANY(months))
      )
    )
  );

-- Messes: Admins and Managers can insert mess data
CREATE POLICY "Admins and Managers can insert mess data" ON messes
  FOR INSERT WITH CHECK (
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role IN ('admin', 'manager'))
  );

-- Mess Members: Users can see their own memberships
CREATE POLICY "Users can see own memberships" ON mess_members
  FOR SELECT USING (user_id = auth.uid());

-- Mess Members: Admins can manage memberships
CREATE POLICY "Admins can manage memberships" ON mess_members
  FOR ALL USING (
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
  );

-- Manager Access: Admins can manage manager access
CREATE POLICY "Admins can manage manager access" ON manager_access
  FOR ALL USING (
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
  );

-- FUNCTION: Handle User Creation
-- Automatically creates a profile when a new user signs up
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, email, role)
  VALUES (new.id, new.email, 'student');
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- TRIGGER: On Auth User Created
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();
